version: "3.3"
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: OTMwoNGFJGrjgfiGFLvdk

    volumes:
      - /home/run/docker.sock:/home/run/docker.sock